server:
  port: 8050


spring:
  cloud:
      function:
        definition: processOrderPlacedEvent;processPickOrderDetails
      stream:
       bindings:
        processOrderPlacedEvent-in-0:
          destination: order_placed
          group: riderGroup
          content-type: application/json
        processOrderPlacedEvent-out-0:
          destination: order_acknowledged
          content-type: application/json
        processPickOrderDetails-in-0:
          destination: pick_order_details
          group: pickOrderGroup
          content-type: application/json
       kafka:
        binder:
          brokers: localhost:9092
  cache:
    type: redis
  application:
    name: rider-ms
  datasource:
    url: jdbc:mysql://localhost:3306/rider
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}



management:
  endpoints:
    web:
      exposure:
        include: "*"

#eureka client config
#eureka client config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
