server:
  port: 8050

spring:
  cloud:
    stream:
      function:
        definition: orderPlaced  # Name of the function
      bindings:
        orderPlaced-in-0:
          destination: order_placed
          group: riderGroup
          content-type: application/json
        orderAcknowledged-out-0:
          destination: order_acknowledged
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

  application:
    name: rider-ms
  datasource:
    url: jdbc:mysql://localhost:3306/rider
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    io.netty: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


#eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/