server:
  port: 8081

spring:
  application:
    name: "user-ms"
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    io.netty: DEBUG
    reactor.netty: DEBUG

#eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


