server:
  port: 8081

spring:
  cache:
    type: redis
  application:
    name: "user-ms"
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  kafka:
#    listener:
#      ack-mode: MANUAL
  cloud:
    function:
      definition: processAcknowledgment
    stream:
      bindings:
        sendOrderPlacedEvent-out-0:
          destination: order_placed    #topic name
          content-type: application/json
        publishPickOrderDetails-out-0:
          destination: pick_order_details    #topic name
          content-type: application/json
        processAcknowledgment-in-0:
          destination: order_acknowledged     #topic name
          group: userGroup
          content-type: application/json
      kafka:
        binder:
          brokers:
          - localhost:9092



logging:
  level:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


#eureka client config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret:
    sachinSonarSpring!@#ABCxyz989&23211!14tSpring

#Razor pay configuration
razorpay:
  api:
    key: rzp_test_NqiZAZv7vcqJe4
  secret:
    key: EVGUJQO3YpUID6CM6DRHpGQb
