server:
  port: 8081

spring:
  application:
    name: "user-ms"
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
