server:
  port: 8081

spring:
  cache:
    type: redis
  application:
    name: "user-ms"
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  kafka:
#    listener:
#      ack-mode: MANUAL
  cloud:
    stream:
      function:
        definition: publishPickOrderDetails,sendOrderPlacedEvent,orderAcknowledged # Name of the function to send events
      bindings:
        publishPickOrderDetails-out-0:
          destination: pick_order_details
          content-type: application/json
        sendOrderPlacedEvent-out-1:
          destination: order_placed   # Kafka Topic, to which the order placed event is sent
          content-type: application/json
        orderAcknowledged-in-0:
          destination: order_acknowledged  # Kafka Topic to receive order acknowledgment
          group: userGroup  # Consumer group for acknowledgment
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092


logging:
  level:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


#eureka client config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"


#Razor pay configuration
razorpay:
  api:
    key: rzp_test_cWfbuLENrweRjB
  secret:
    key: TFT6Y0u3M619bQ1UOztqngsR
