server:
  port: 8081

spring:
  application:
    name: "user-ms"
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderPlaced-out-0:
          destination: order_placed   #Kafka Topic
          content-type: application/json





logging:
  level:
    io.netty: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

#eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"


#Razor pay configuration
razorpay:
  api:
    key: rzp_test_cWfbuLENrweRjB
  secret:
    key: TFT6Y0u3M619bQ1UOztqngsR
