spring:
  application:
    name: "otp-ms"
  datasource:
    url: jdbc:mysql://localhost:3306/otpdb
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


#eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

