server:
  port: 3240

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #fetches only the required information from eureka server
          lower-case-service-id: true

#eureka client config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Api-Gateway"
    developer: "Sachin - Sonar"
    description: "API Gateway For Quick Bites Project"
    version: "1.0.0"


logging:
  level:
    com:
      quick-bites:
        api-gateway: DEBUG
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
