
server:
  port: 8083

google:
  api:
    path: https://maps.googleapis.com/maps/api
    key: AIzaSyAaJgPAemtEPuzIq22YSvv_PaMcjIHwgUI

cloudinary:
  cloud_name: "dxjpbraxt"
  api_key: "457646547321669"
  api_secret: "u_jLcawfzKSqD305ftNBkPD6iX8"


spring:
  cache:
    type: redis
  cloud:
    stream:
      function:
        definition: orderPlaced,orderAcknowledged  # Name of the function
      bindings:
        orderPlaced-in-0:
          destination: order_placed
          group: restaurantGroup
          content-type: application/json
        orderAcknowledged-out-0:
          destination: order_acknowledged
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
  application:
    name: restaurant-ms
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#eureka client config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true



info:
  app:
    name: "Quick-Bites Restaurant - Ms"
    description: "Restaurant-Ms Application"
    version: "1.0.0"

logging:
  level:
    io.netty: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}



